/** Shared by installation, third-party updates, and marketplace self-updates. */
export const reviewChannelZh = `【安装通道与授权】先确认目标是当前会话所属实例的 profile，而不是工作区名、进程工作目录或默认 web。优先使用当前会话实际提供的官方 plugin_manager 工具；不要假设工具一定存在，也不要自行拼接 Remote HTTP 请求。先以 action=list_bundles 分页读取清单，核对已安装包、实际版本和管理范围，再以 action=install_bundle、target=已审查的精确安装引用、enabled=true 执行安装或更新；不要传入另一个 profile。升级时以实时清单为准，未找到原包应停止说明，不能悄悄变成新增安装；已是最新则结束。

profile 名不区分大小写为 desktop 时，CLI 禁止管理：禁止调用 dsh plugin，禁止改装 web、手改 profile 或直接运行 pnpm。没有官方工具时，给出已审查的精确安装引用，交接用户通过 Electron 官方插件管理界面安装。其他 profile 仅在工具不存在且核实 CLI 对应同一实例、同一 DSH_HOME 和目标 profile 后，才可用 dsh plugin --profile {profile}。工具拒绝授权、版本不兼容或操作失败都不是换用 CLI 的理由，不得绕过限制。没有可用通道时明确报告“审查通过，尚未安装”，不要要求用户更换目标。

只安装实际审查过的精确版本或产物，不使用 latest、版本范围或笼统 update。管理工具要求授权时交给用户确认。遇到 pendingBuilds 时展示准确脚本名称与风险，获得用户对本次这些脚本的明确授权后，才通过官方工具的 approvedBuilds 继续；不得自行修改 allowBuilds 文件，不得添加版本兼容豁免。`

export const reviewChannelEn = `[INSTALLATION CHANNEL AND APPROVAL] Confirm that the target is the current session's running-instance profile, not the workspace name, process working directory, or default web profile. Prefer the official plugin_manager tool actually available in this session; do not assume it exists or construct Remote HTTP requests yourself. Page through action=list_bundles to verify installed packages, actual versions, and management scope. Then use action=install_bundle, target=the exact reviewed installation reference, enabled=true for installation or update; do not substitute another profile. For updates, trust the live inventory: if the original package is missing, stop and explain rather than silently making a new installation. If already up to date, stop.

When the profile name is desktop (case-insensitive), CLI management is forbidden: never invoke dsh plugin. Do not substitute web, edit profile files, or run pnpm directly. If the official tool is absent, provide the exact reviewed reference and hand off to the user in Electron's official plugin manager. For other profiles, CLI is allowed only when the tool is absent and the same instance, DSH_HOME, and target profile have been verified; explicitly use dsh plugin --profile {profile}. Denied approval, incompatibility, or tool failure is never a reason to switch to CLI or bypass restrictions. If no channel is available, report "Review passed; not installed" without asking to change the target.

Install only the exact reviewed version or artifact, never latest, a version range, or a blanket update. Let the user answer management-tool approvals. For pendingBuilds, show the exact script names and risks; continue through the official tool's approvedBuilds only after explicit user approval for those scripts in this operation. Do not edit allowBuilds files yourself or grant compatibility exemptions.`
